

test = """vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw"""


data = """tdltdtmhlRNCBcwmHr
WDzDPnvvGnsWLWpGJJHRzCCRZNBRrRwMNwHH
DsDsQnJDnWsJnJvrQDPJddgShFQhjljqhggbdbbt
LqvbLLTdvlfdqTLtbvDSRHPhHmRSnndHnHRM
jswsGgzwsNgNWNwGJzVrgSHnhHHDmShmmGShnMDPRn
JMNWzVwMpjpLpTfTLLTf
HnQBjMjPQmRMmJCmBPGSFTSVWcNNGQQGGGTV
dgstqdtsbwrzddvrvdwqzhrWSFllDSWGDWFGDNsDDWSTHT
gpqZwwzHZhwzMJBmfZnnJLCL
PJHbTPCmLdTtLtRtBvzBrWffft
hnpTqhMncpFDppDqqNVFVvWzvNWNvfBfzs
GwZccTpgnDSDDZQdCZbbClbCmm
bnZnRZZZRlpGBbfRJjBbMfhCHwfsHShschMsHCww
LqVtqVmtLQvVqqLTFFvLDMhDMpMhwMSLDhsDCH
mFQWtNggVQQgmdgpJGpnnZJjbWGBRZ
GsdGrGqvLZqWvWWdrPLdfvsvSJDDcQQhcTbFbTcCJLSJShcJ
wmBlnjwjgHSSDQjfDDfF
wggpmwmwNnMlHRpttRHmlPfWzdGvvvzrZWVvMrPvvZ
jvlvTvTvTvcqTdZrdnGlVfNgspslpfGGnM
BWQhQzQwmhwWHbWCSRMRgjpjVDDRgDgVffgV
zLHQSBWmLcjdPjLLLZ
BjjLnRzBnRmTSTBhpBmCjnLqNPGGVNZgNgLGddZVNVdf
wDDJJQJlJtHrlwFFPNGGfZbbbglgfPSf
tFQssvcDJtJcFcvwHtBmnSCvRmzzhpSCWvmC
GvPVvVHPgzPMcFvDHssdpCpsnpHnsj
gmhmSRZBJTTTmSBZhhrqSBLRCnsBjjnbjBdbdbbdnbjwwBsj
WlrgrRgJSgZSJJJTZRtvVzvGtfzcVFcMzlGM
QSZwwsBZZwjsndFsMPHLzTLLLz
tpJfgHghmvqpNWrrTMrMMRzPrMPJ
ghgghmlvmgNWgmWwBQcbGGSclGHjjb
lhlnWGGFWZhDfgFfWDfrhgrRwcccqcZQBQMwcqJMTMRMqJ
jVdpSLPVSjtNdjdPtptzLNPPzcBzwCQrCcTBTRqwwqMCJTcC
PNHdpPLHtHtjdLghnHWvrvnFlFnf
qttvqPdCtLrqRgfpgpMgSfSWvM
TJccnTDjjDlDhSpfHdhpTpZf
wldwmJdwmsstCsLzBsBCGP
ddpCGpGpnndnpWqdVVpDGfDGFzSsFSZzBJShJsVtTstssrsr
jbvPLwFjztJBtvJz
wjggcgPFLlLwPFNwHmNPQqDRQfCRGCGqnpcRqQnn
PmmGhLLcgZbPQnqH
DlVsvvrvvvrsDJLRDvvCHbpBqpnbQnggbWZbggVW
vJRTSSRJClCCDwTJRfSfCsGzMLmGmzmjGcfmdFNNNtfh
vcmmMvfctfjLjvvRbLdHSnQSgQFnghSgQQSSjT
WzVbszVNHnTsQFgZ
pVlGlzrbDNrDrPpJNNJpVdBDvLdqvvvqqdBqcfvLdq
gfzgzPDVZQDDSqBdtFfdFdvqBB
MrwmTcJJsMwNmJdvFqdFGGtvvsGt
HMmTTwcJqcrTHrjjczhZQgzghgQHhnhhHh
BffBVgjPwPPPJwBBVJfDDsgrdZdcZqlcSnSncRNzHzZljNqq
CmWFbCmFvMtLLQCTbbbLtRqdSZHcdnqqNqNTRlnqNH
MpthtSMvFbvWPVDrsDgpPggD
VVRntNwmlvhGccPNfS
QZcgZppdrZQTzrBgCbrbdQrBvjLssPjSssMsfSLhTPPGvLTP
ZZcpJZHpgCgpppdrJRtVJFqVFVDRWJmtVq
dpdhtpjHtnpFRHdjRnwspMQmqpqqmVqmTVJQMmff
gSCcBCBCcgwDBLSvcLQQVTMmfmMJDqfTrrVV
gSwPzLBbNCbFnHHjhthh
dLNrRmqLqRgCNNrCJrSqqSQgjDWnGpGjDjspnlslGHnnjsQj
vVTzZFVttVBMFbFfffVVmVtHWpDspjHWWWbGjjjDsjWllW
hwFFwztTzvZmBzVfqhSSNPRPPCRPRJCr
BjfcmzCCTtNBNjcTDWwzPzDMMQPDPMws
lGpJFHnlSlnZbGnQQSBLwSPPLMsDQh
JFHHpbnZbGbZgvTmqfNgqCcvjB
ShhpqjhhVZmHhSJSSnLzdNRNTjLwNTNTzv
QffRWRrMGwLfgNcNgc
GQrQDPRBlGlsGrWtrtPDPbWpqhZqSqJJpHZSVhVhhmmBZF
ZlVVDTtTrzFDrFfB
NNGbJNNNNmpWBNbNWmjMfdjmFfPdqFMrMj
NQvRNvSRHSQBgRGQJJQQHTtcVLlVcTwVTllnRsttZs
fjsDhJsVDcVJVljFDqLqFlnnCFbzbCCCZCzCtCZrnCCM
HwQNrHWNPGPHMZCvMCbzzvHZ
dBWwWPPGrGwBlcjDlcjcjldL
NCLMHJZqCHHHMFlNBZtTZRvtStZdcRbc
wDrnpbswVgsrsWmGpDpfpBQtRSTmdvBjTjtBScctRm
gwzgbGDgpgFJMzlzPJCC
SpnfPVqFnGfPGggqfGbjZZrtWrlRlbHpZjRZ
mmJmdJBsBJsDwhJBQhTZtzdRltrrRlrtHjjl
NBscQhmsmmQLLwLmhhwmcSSGfnfSFCSMCPfHCMqG
hvVnPwZwVzQrhrVhPPPrpQVDBgMMlSTLZsgdDTSTdsssLd
RvFCqCGfbFCRbRmSBMMsLBgdFDSgdL
cRGjRWbWjvtPvrQcnr
LzLNzhpcRRcTmNDzRhTPDjMvMnVlMgjngSMrMzrQQr
tfbWfWcWddFcGFwfswFFFCrjjvlVbrQjSglSQMjgvlgl
FHWGCHCCGcwfswqHdHqwwmPqRJDpZZNRJPRPPTTJNR
gLHLLhTjZVMwMRSZZS
GdqdtlPvnQPPnsRw
tNNGvdtbdmJmHRTRJrFr
QjjdjGDvdjwpZsssvsPZFZll
mTWWMWzbPHmZwHHw
JwTbtBztMVLDSpjVtc
SZSBWtBSwnTDFSDD
CsrJWmmPrPQmpzsPmssssvnTFhvTnPhnFDFfDFnwqF
CCCCzprgrJJCgmVcpJmWLQZddHlGbMbdZMbtZNNcHHBt
fgqqrZLqZqFzFFWzZzgPPbnMNNNvQnpQnQbNbpcHNP
SdwdmwCClCCwldhRSmsvpbncjQbNNQMtjQnMvS
mDlwhMRlCwDCTVwVJRdGgfzLLzzGzGFWqGqfGD
CnVvCqvnRqHVqnWcMFnLmLnMMm
ZrdzbzbrdwtQdSfdcmmFMBWFNFWLwNNp
QFrQtJDdSZdDVHlVCPssJRll
qMpGGmVNHMGVjRJJGfRgQtjQ
flsTZCwDwWcZZPCrPZZWgLLjdJJQSJTQFSgQJJRt
ZcChshwZCDvlCZCsPHMHzqNzBmMfmBBMfh
wCtZtzCnPldZSdZp
VMspbMHspbshbPBLFsdcsLBdLs
pRrQHpNbQbrqRqJfnwfwzR
DPPcDlPwNdNRJsccpgvwBBvqGGQtqrCjwr
fMSVrMWmLZqHQgLggCHH
mZZWVTbTWWfnMWrbmznfZfsPNcdsdpRcNJplbJNcNRNl
ztlNSLhplhBHwwBBMBtv
DnVVfcGbVnGRZGgvPMpHBpCmJMDP
GnZdZZnbdpVcQjQQFjjqrlNWlrsNrFNLLsWqSF
bJQgDRfjDbJbRMTgSSPzPHCNhzQHHszz
wmnwFmDcwFGvpvwGnSWPNPWzPHhhcWSCNz
GpDtmvrdGvvBmZrLTjZRTqTjblbMfL
gBhZmtHhhhwTJqwDFqGGqPWqDb
rRLRVTrjCrCVdFjMbvGPPGDPvW
LSsVdrRNRCCffCSllQNBTNgNlmhHBJ
lCzCCDMDlzzlZtttWDnDCZPbVGLhSmSLGbSgGPgVZm
sBcNsqTQwRQRrBgbgSbPTLVSnLmV
wcqrjQsBBjdCzjdnCv
ZgHVtMQVVgvQjjtzdzfdFHppfmzwpz
CsBrBLLJSrsRCvnGvfRdvF
DbBJTJDLrJDqqqrrhJsJqVWthWlZZlZjMPZltvtMjZ
bsHlrwlnwwQJsqmJnqsPSLzTLpPGPSgPPPWmLT
fdvBtpMDfpCCfBcCcCBtDfFSgTMTGSTRPLgPWGzGgVgLVz
NDcjcDZjBCdvvjdvhlbJnprjnnbhwrqn
zRpLMMqjgMggqLDqDRVGNGdhGtvGGnvGnrznGB
VScbcZPJZWZlZbbHSJQJGtrGvtmdBBGmdGBrdn
cbPsZcPCcWfCZPcPQslljpDqwfqVgRLMTRjwVqLM
QtRWhjtsbttQtnbbQvsrRBfDNdMGBLZLVVNVGNLGWd
JwllwllJmCwzPFSJzwwTBZLDLdBBBPLZZBVTTL
ZwFSSmpwzScFSmggHQjbQvjvscQbrtnjbs
WMLWnSHSMnHjPVMVMVVJGM
zQzRcmttdftrtrdZZRzDtPZppphsVbjGbQbJTTsCbsjppG
dmrDtqfzrmZtqDvdfmZmtdqzLNlgnwgWLNvwFWgWWPNFSFNN
hvSrMwqljjBHvqhHsHshqnrZcCCpfCZZCCZZCcCfCZ
QDVTRFWlmDnpLnnPTPCZ
DVQVtmQRWRRGFVRWVvlwdShBvvSqvtjMdd
pnMQbbnDQMNMDQsnTplNTDvqPGHZGcvqmCqvmqZqmlqP
dwJdBBwdJJwLJBLSRJczWmHPzqWzzHGmvPRHGG
LrdFgSSLBsDMFFcbQb
NSnwvSPPVNnPTLVpRvVvRnqhhQQzHhLbzlqcqHzmHHqh
DFMMfBffgZJtFsJgwdDHGHHzzmqhhHQzDQGhcH
dMrZMMgFfFtZJZfBWMfVPNwPpNwPVSNVjjVWpN
dNlLSvLSdNlhphlhlWfVFFbZHqjjHHvqFZQHCQ
BcrTcJfRMRmrcbqcQgcHVCVF
fBzTJJRmfPPmnppdNwhllwlz
GqfSSmPSFwSCmFBwfQfQBfGnggLrhTrJBDDnrddsJDdLTL
cHHvVtptbzbrTQJTggnTQv
QRVbbQWbpZbVQVGfRmwfFwmjflPP
zzBQJmzQPPlddpJWlzzfdpfjvLvgmvFggMFGDVvLGHVFvvtM
CCSTrCncrhcCcwhRnCqCttFDvMFvtWtVHvFhvLVv
wCTNCSRnbnpWzlBpJspN
PTzTPlrrfrbzmftTTrrjPMsNNFZQgQHVgMtNVFMgFF
DpGBcpvdZhccdGJhqDBphZhdVRQVQQVsqFwMRwFgFNHMHwQQ
SGcLGpdGnBhDJppSDZlPTTmLrmbTLTmrZL
PzmhTqSzdDGcDhzdJDPBmJnrdVppNVVtgttMVrNnMMnV
blbQbWLvlWffCjlGCWwsnLpnpMggnpspnsrg
fQRbCZRfFZvZRQHRvHjmGmTFPcBmDhBGTzmGqS
JJVJfgJfVDdfDDcpTBgdwQMQZQRZQZwmlmWwQGcm
ttzzjjzSqPzqtqzFrPvzwNwMlMRNnnwnllSmmmQG
FCvvChhsRVhhJBdB
rbQZdRzBFTBzZZcclntHnlfJlrNgngfS
PPqGjpPGqpmDmDwqPDVnlNpnJfnnnglJCHlNfC
MMhhjMwwPvZNZTvLTZdL
ZZGgVgwfQNVNLfZsPqRsVTDspTpsqs
jdjdSbmMdMBSvMgBcWpsRpTWDHWTvRPs
httmBMhbBBjCdzShfGzJlnQLlgGGZwww
gLSLMCbVSGRPdTwtjtVfdt
TpzJpFFqmzpscslBtddjlwjjDhhldhvP
WpsTmJpHssqnHMGLnGSgbH
RRBCpJJplCchWJJHCHCvjdpMzFzrNvVgFrrMzz
btLLPGSQctnZnPwwSjgZjjjNNrvMvVrrjV
tmLPGmnbnsLLwqQPSwqGbwDfHlHWBWlCsffshDCBfWcJ
GhDFZFGZzzbCdZbZVlfv
bPNWSbSJSWSJPBBLLqClCltlwlNmllwvCQfC
PgPLqgqpWcWJJcnqJccccGrjbHhDRGMDGTDbpRhbFF
VJRffrVJvDzcRcFFbpSlQLHlvtlstbbt
NmNqPhPqPZhsQLQwSRpH
dWRnRdBmMBWgjCgVGjFcCDzf
nhhQFDmVmDGhmFpgCgBpcpHqncCt
fLLZbljhjjscCggBCLCL
PhMRhNWddWNjfRdPRfWNfVmvQFVQzVMJJDJGrmQGrQ
PNQtsHvZtsQgQLPsPtHZbfzRffRzMMqRqpzbfqng
jDwCmhrDlhBhBldrzJMmfFFbSfFnqpFb
jdljDrDrTBBnGVNcGcQLQLQPQL
MjzrjZvWQRHtjQdS
JFJlDJbcbvtRQmQbQQdf
JqNDBVNpqCBqDBCBVDcNVBqNMWgGZTPZgCrPzzvghPwrwZgG
gzggttLNDFztFCNWzrLttmFddSjsdJsgZVSsJjwjgbgZVG
pPPcqpnqHMpcRbhhMMpThvnwZSjZvdwZvwdZSBvGZSGVZZ
ThcPlHbbPHRnlRTHnMhpfltrNLWzCWWCztzffQLLDmDN
SlNJRpCGTmdFFDcbqJZFFJ
wwnWPHgsLPlVVfssLcZcjjzrDqcFzcgchZ
WVvQHQPfLwSGSvCRlNSd
wWnWcpWDcwHcRdJQTdmNsT
hprqBSvZNjFdFjsq
fSfpvhLBfltMCLzWzC
fdPfPwPmdmLZfNWjWszQNjjN
MBRSBBRBChMRQWhlmVWNsmzm
FvRcSrcRrtvrRrvrrrmcwGwLnTHHqGtwZwHdGPHP
tFPlJcDJdvLZvFlcvlHtQRthbgQjrhsgQgNr
qCnpGMnTTVwCCMnqwWfpChQHRbrgQjsQmmfrrHgHrH
GMnTSBnVTnBGbLlDDvFBLDbF
rJhPGdLSWnnrdqLhPPWGjcZZffjcgNdgNgRcNfwf
mHsDTQlsQBvWspTHzpmCTpcZgwZjZfZNRFwRjRRNMHjZ
vCzDDQsDDvbllWTllCDCCTSLbqSPVqSnJLGSqrPLtVnP
sSRdHHHSRhjShVHWVFJdQPNFpGCrQCCfflqlPvfN
gLztmctMwnBtTzMppBCCrGfQlQQqBN
bbbncfzLmmmnnZLgHZWjhsjVJjHRVSdR
bRgwCHfgfCCttRbdRLHzzGDnDnLBhmBGzvmFZD
rssprQlqlTQGNPcJGVsTBDmWzBnPnhWBvZZDBvDm
MQQTJTNGNcqrNwMwwHRdRbdgbj
sBnnsDLDBCsLTngnZLcdmppCdmpRJwJJQdMRMP
NlrTblbNNbwRPpjjbPdJ
GlztrhvfGqltqzWrcZgFZVSWWSTSncnL
FLJqLFRjzFqzJddlLfNNCjPrGSHCPHNVNVSH
TWTpngssgcPgNGPc
pGMDZpnZBMDsTTTnTsQWWZTRlbvdfZlLflZzJfdqvdRbqf
ClsJpCgsppMbFFFbHp
PvQRPqQPvRdwLNZLZqqwGPPPNTbjMcFcfHjHcMNfBNHrcDDM
GLRnzqzdRqwdZnLLPqqZdQGsVtsnlWCVVWsgtWSSVVhFWt
LNLSJjQDLlzRGwTTzQfT
WbZqchqMZqZWbmdZbhTrvPmGvwfHRHGTHRwH
dcfChsWWZgbfWdhCbgDNFBBDjFNBjjVNpD
HjCLsHJHCjnNVHdCnHtJdtQQgQDhFGFDLcwFDBFMMDBT
vWrSWSbSrRqmzlWlQgRQQTcRMgMTMFwT
bzrpWWzbqrpnZsJwZVpC
FhlfrNdTrtFdtrrrfcZBMdpZcHHHZMcccv
PmbjVDjwQbbjjVpDDvpzBZSSMsvG
jmbVjPVWqVmgJgjmmPPQjmqlCMlftnftnNlTTLLfNfrJtN
PwMWzqwWbFwznqNQQhffQjJfnhfJ
mmdpgmttDrpgpdmZdHmgNsQVZvJNMQvVJffsZVQf
pdcBrMgDgcgrrHPcFSFzzqzFFbPS
QRJJtSfJtQtjQRnSnNssTNdgsgdwddRWcm
qHMDhPBqbqZVzbddTcVwSmNWNVcc
BFCZbqPbHBPMhCljvQSvGCCpnj
HSzHNHlNHmBSHSBFrFFgBHVVqbQLTTcLtqDsDTBTDcDp
CWQZGCWfMZGqbTbtpLsbWp
GwjhPCRZPQPPCPwmzSNzzzmwzlzSgH
GgTvJbpJGvPVHZZZLW
cwWdnwmWnfwZDBHHNzZBVf
nhjjmshdwmSjsnmwrrQrtbtbgTTgrWth
lFBTtcnlcFlppVpttcFZVhTTDDLCHDSDCjDCMSLZDWdDDSjD
mrfsgMfRRwwPffJfbdDdgWGLGLSDjSSWdC
MmfNPwPzMzlhlFlplV
pRVgVsRzdDVJJJRttZTnnLrGsrGssG
BjMvMBWmjWNWSWrLGZPTHLSLTrZr
LLMWQjfvmljLBRVJfbChfVgJRz
RPDsdnVrVnVzScStjpFSjV
BTLBhMMBpSMsMjZz
hwbBgTsbBbGrGHvGrvDnPH
nzwgtSFRqhDphDwB
CmWCrrmrVPGCDTbpvvvhsZDG
VdNrlWHpmQzSMgJFdRFz
jrhZtczchvvFCTmCDlDMrMDT
bHbLnbbwLnWQpLQgQVpQCTDqdmwqmDqCdDCSlmdd
sgVgglblptsfFthtvR
LctzWvrzTWsvWBfvBzdJQSdQhQQfpDJJmmDD
lMRwjlwlLnZwLHLggQDRGphdFDJQdSdJJQ
CjPZCVCjgPwgWqWLqzzcWsVq
JNWHsPNsJNHBnfnnqfqswcctDTmPCRmmTRtgCdmD
rjGrLrbhGRZVGQhphbbmDgDZMDMwdwDcCMgcDM
zvbLvVpFvjzVhbQjGjHlnflJFlWRqBWWBJBS
NfCMfGNdGqVDhWBvncLllhBgcmgL
bJbRbHHtRtJtZTpSRtsLDLzvcvBmgnnnJlsm
SbbbTRpbQHSbbwHZZTHqfCNMfqFWGNGVQMFGDC
MdzwdMpVwVNMHQMJNcHM
mDtcPDqWnDqgnGJvLHTJHJ
mmjhhRBRBcdZrcdRCz
lvldsNpNGCGgCvCGggDLMbMmrdwnjjZdLLwrjM
HWHtPHSHPBnrmZjBbwwC
tHqWRtfttNlDClvNqs
BTRNQTQTTBFRTglDwzztDgCwLF
jZsMjqgdrrzzSbsDSwsw
jWZrMgMjGdvrWWvrWMfMfZTBHTHQBHBQNpQRfRHNpnRT
GRgFCPhnBBhPwZPnwdbWMJMlcJTLLlTlRT
VQsvVvvVNzqsscTVSLbWTStTJW
spfDNpvsnPCfhBbh
GhWSgWphprhQqqndQd
MvZRjjLcCzwcLnHfdTdgfFHQ
wCczcCgRMwRRNCtjMCtCvlBmVDGslmPpmWWNVGSpWV
PZqgTbTZvFgZbZnFvPlBsVqsGBlGVzGsqVls
MMhSmHHfrfrSrjMNfcjrSRBlBVzGVpVGgGVCGslGNd
rMhQQmDSQMjMtZvPTTnJvtQg
TNGWlqVpmPssnNssWLtRfCLbjCCwPgLjfg
ZSHvHczFBBcHhJHFvhHcSFgrCgLbfgfbwrLTtbjwLwJr
BMzSQzcQznlNQTQsnl
FVWDZDZHpDdtZlqZqZqljfNmsNFPjbbPbPRbFFjm
MJSGMghngrccvSrSzMrsQbbRmjmQmjtNtbfB
CMnvczGChCCwcgtpDDlLLLwVHdlHTZ
fTTzbQzhDwwbCnZnpbgnHncM
mGtBRBFmsRpVGMzpnnGL
lFNqtdsssrRFBltSFRFlSrvfDSWWvwfhhPJPjWfQzPvf
GWWWQlpSZzrQnjQdRHVjdjTRvddddB
ztthMtCmffcChJhChfCJdLddLBBgvqdvBBVBcgdq
smbsmbmChCJmJffPmhNthDtZwnFQZQGpSrGWGQGZpQZzWP
ZDzsjjFLFqsQzFsZqDzBHGtBHpmgdNGmGBtLBG
hbbMMTcWhbwnJPlwWrnPbbVGVNndgpVVHmdNHVBmmmtf
bCTPTclcgRZQZCgs"""

print(ord("A"))

def f(let):
    if let == let.upper():
        return ord(let)-38
    else:
        return ord(let)-96

def solve(data):
    lines = [[i[:len(i)//2], i[len(i)//2:]] for i in data.splitlines()]
    print(lines)
    tot = 0
    for a,b in lines:
        for x in a:
            if x in b:
                break
        tot += f(x)
        print(f(x), x)
    print(tot)

def solve2(data):
    lines = [i for i in data.splitlines()]
    groups = [lines[i:i+3] for i in range(0, len(lines), 3)]


    tot = 0
    for group in groups:
        s = set(group[0])
        for g in group:
            s.intersection_update(set(g))
        print(s)

        for i in s:
            tot += f(i)

    print(tot)

solve2(data)